services:
  butla:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      traefik.enable: "true"
      traefik.docker.network: "web"
      traefik.http.routers.butla2.entrypoints: "web"
      traefik.http.routers.butla2.rule: "Host(`test.but.la`)"
    restart: always
    networks:
      web:

networks:
  web:
    external: true
