default:
  default: https://dylanbutler.dev
  /github: https://github.com/dbut2
  /linkedin: https://www.linkedin.com/in/dbut2/
  /strava: https://www.strava.com/athletes/dbut2
  /lastfm: https://www.last.fm/user/dbut2
listen.dbut.dev:
  default: https://www.last.fm/user/dbut2
listen.dylanbutler.dev:
  default: https://www.last.fm/user/dbut2
