services:
  scheduler:
    image: docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/sh
    restart: always
    command:
      - -c
      - |
        echo '* * * * * docker run --rm \
        -e SPOTIFY_CLIENT_ID=${SPOTIFY_CLIENT_ID} \
        -e SPOTIFY_CLIENT_SECRET=${SPOTIFY_CLIENT_SECRET} \
        -e SPOTIFY_REFRESH_TOKEN=${SPOTIFY_REFRESH_TOKEN} \
        -e SPOTIFY_PLAYLIST_ID=${SPOTIFY_PLAYLIST_ID} \
        -e PLAYLIST_SIZE=${PLAYLIST_SIZE} \
        -e OTEL_SERVICE_NAME=${OTEL_SERVICE_NAME} \
        -e OTEL_EXPORTER_OTLP_PROTOCOL: ${OTEL_EXPORTER_OTLP_PROTOCOL} \
        -e OTEL_EXPORTER_OTLP_ENDPOINT=${OTEL_EXPORTER_OTLP_ENDPOINT} \
        -e OTEL_EXPORTER_OTLP_HEADERS=${OTEL_EXPORTER_OTLP_HEADERS} \
        ghcr.io/jamesblewis/triplej-playlist-generator:main' >> /etc/crontabs/root
        crond -f -d 8
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REFRESH_TOKEN: ${SPOTIFY_REFRESH_TOKEN}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      PLAYLIST_SIZE: ${PLAYLIST_SIZE}
      OTEL_SERVICE_NAME: triple-j-bot
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_EXPORTER_OTLP_ENDPOINT: https://api.honeycomb.io
      OTEL_EXPORTER_OTLP_HEADERS: ${OTEL_EXPORTER_OTLP_HEADERS}
