services:
  scheduler:
    image: docker
    labels:
      io.portainer.accesscontrol.users: jamesblewis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/dylan/ghq/github.com/dbutlabs/home/jamesblewis:/jamesblewis
    entrypoint: /bin/sh
    command:
      - -c
      - |
        echo '* * * * * docker compose -f /jamesblewis/compose.yaml run triple-j-bot' >> /etc/crontabs/root
        crond -f -d 8
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REFRESH_TOKEN: ${SPOTIFY_REFRESH_TOKEN}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      PLAYLIST_SIZE: ${PLAYLIST_SIZE}

  triple-j-bot:
    image: ghcr.io/jamesblewis/triplej-playlist-generator:main
    labels:
      io.portainer.accesscontrol.users: jamesblewis
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      SPOTIFY_CLIENT_ID: ${SPOTIFY_CLIENT_ID}
      SPOTIFY_CLIENT_SECRET: ${SPOTIFY_CLIENT_SECRET}
      SPOTIFY_REFRESH_TOKEN: ${SPOTIFY_REFRESH_TOKEN}
      SPOTIFY_PLAYLIST_ID: ${SPOTIFY_PLAYLIST_ID}
      PLAYLIST_SIZE: ${PLAYLIST_SIZE}
