services:
  minecraft:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: "PAPER"
      INIT_MEMORY: 1G
      MAX_MEMORY: 16G
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsX-2.20.1.jar
        https://github.com/EssentialsX/Essentials/releases/download/2.20.1/EssentialsXChat-2.20.1.jar
        https://hangarcdn.papermc.io/plugins/Blue/BlueMap/versions/5.3/PAPER/BlueMap-5.3-paper.jar
        https://hangarcdn.papermc.io/plugins/Multiverse/Multiverse-Core/versions/4.3.13/PAPER/multiverse-core-4.3.13.jar
    ports:
      - "25565:25565"
      - "19132:19132/udp"
    volumes:
      - "/mnt/mc:/data"
    networks:
      - web
    labels:
      traefik.enable: "true"
      trafeik.docker.network: web
      traefik.http.routers.mcmap.entrypoints: "web"
      traefik.http.routers.mcmap.rule: "Host(`mcmap.dbut.dev`)"
      traefik.http.services.mcmap.loadbalancer.server.port: "8100"

networks:
  web:
    external: true
