name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, dub]
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up --build --detach --force-recreate --remove-orphans                    
