name: Deploy
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose -f compose.yaml up --build --detach --remove-orphans
          docker compose -f bma/compose.yaml up --build --detach --remove-orphans
        env:
          APPLE_EMAIL_USERNAME: ${{ secrets.APPLE_EMAIL_USERNAME }}
          APPLE_EMAIL_PASSWORD: ${{ secrets.APPLE_EMAIL_PASSWORD }}
          CLOUDFLARE_API_EMAIL: ${{ secrets.CLOUDFLARE_API_EMAIL }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_TUNNEL_TOKEN: ${{ secrets.CLOUDFLARE_TUNNEL_TOKEN }}
          CLOUDFLARE_DDNS_API_TOKEN: ${{ secrets.CLOUDFLARE_DDNS_API_TOKEN }}

  jamesblewis:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker stack deploy -c jamesblewis/compose.yaml jamesblewis
        env:
          SPOTIFY_CLIENT_ID: ${{ secrets.SPOTIFY_CLIENT_ID }}
          SPOTIFY_CLIENT_SECRET: ${{ secrets.SPOTIFY_CLIENT_SECRET }}
          SPOTIFY_REFRESH_TOKEN: ${{ secrets.SPOTIFY_REFRESH_TOKEN }}
          SPOTIFY_PLAYLIST_ID: ${{ vars.SPOTIFY_PLAYLIST_ID }}
          PLAYLIST_SIZE: ${{ vars.PLAYLIST_SIZE }}
          OTEL_EXPORTER_OTLP_HEADERS: ${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
